name: spacepad-dev
services:
  app:
    image: spacepad/app:latest
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    networks:
      - app
    volumes:
      - storage_data:/var/www/html/storage
      - database_data:/var/www/html/database
      - .env:/var/www/html/.env:ro
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: 'true'
      AUTORUN_LARAVEL_MIGRATION: 'true'
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  scheduler:
    image: spacepad/app:latest
    restart: unless-stopped
    command: php artisan schedule:work
    networks:
      - app
    volumes:
      - ./backend:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app:

volumes:
  storage_data:
  database_data: