name: spacepad
services:
  app:
    image: ghcr.io/magweter/spacepad:latest
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - storage_data:/var/www/html/storage
      - .env:/var/www/html/.env:ro
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: 'true'
      AUTORUN_LARAVEL_MIGRATION: 'true'

  scheduler:
    image: ghcr.io/magweter/spacepad:latest
    restart: unless-stopped
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    platform: linux/amd64
    volumes:
      - storage_data:/var/www/html/storage
      - .env:/var/www/html/.env:ro
    environment:
      PHP_OPCACHE_ENABLE: 1
    healthcheck:
      # This is our native healthcheck script for the scheduler
      test: ["CMD", "healthcheck-schedule"]
      start_period: 10s

volumes:
  storage_data:
  database_data: