### Send heartbeat to Spacepad server
POST {{baseUrl}}/api/v1/instances/heartbeat
Content-Type: application/json
Accept: application/json

{
    "instance_id": "123",
    "license_key": "123",
    "version": "v1",
    "accounts": [
        {
            "email": "test@example.com",
            "status": "active",
            "provider": "google",
            "isBusiness": true
        }
    ],
    "users": [
        {
            "email": "user@example.com",
            "status": "active",
            "numDisplays": 2,
            "numRooms": 1,
            "usageType": "business",
            "isUnlimited": false,
            "termsAcceptedAt": "2024-03-21T12:00:00Z"
        }
    ]
}
