name: spacepad-mariadb
services:
  app:
    image: ghcr.io/magweter/spacepad:latest
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - storage_data:/var/www/html/storage
      - database_data:/var/www/html/database
      - .env:/var/www/html/.env:ro
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: 'true'
      AUTORUN_LARAVEL_MIGRATION: 'true'
    depends_on:
      - mariadb

  scheduler:
    image: ghcr.io/magweter/spacepad:latest
    restart: unless-stopped
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    platform: linux/amd64
    volumes:
      - storage_data:/var/www/html/storage
      - database_data:/var/www/html/database
      - .env:/var/www/html/.env:ro
    environment:
      PHP_OPCACHE_ENABLE: 1
    healthcheck:
      # This is our native healthcheck script for the scheduler
      test: ["CMD", "healthcheck-schedule"]
      start_period: 10s
    depends_on:
      - mariadb

  database:
    image: mariadb:lts
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  storage_data:
  database_data:
  mariadb_data: 