GET https://graph.microsoft.com/v1.0/me/calendars/AQMkAGMwOTg0N2IyLTMxM2YtNGM3OC1iZmUxLTlkODlkYTZkM2Y5NQBGAAADmjZsXgRn_0ulz0qs3WatIAcAranw5q4G4E6C7jhn9RjFbAAAAgEGAAAAranw5q4G4E6C7jhn9RjFbAAAAr84AAAA/calendarview?StartDateTime=2025-04-04T00:00:00&EndDateTime=2026-01-01T23:59:59
Authorization: Bearer {{outlookToken}}
Content-Type: application/json
